services:
  - type: web
    name: comitezin
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false # Manual value in Render dashboard
      - key: NODE_ENV
        value: production
